name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Sync']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if you're using a Node.js-based project like React, Vue, etc.)
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Create .env file for build
        run: |
          echo "VITE_ADMIN_PATH=${{ secrets.VITE_ADMIN_PATH }}" >> .env
          echo "VITE_SERVER_API_URL=${{ secrets.VITE_SERVER_API_URL }}" >> .env

      - name: Build the project
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # This token is automatically available in your GitHub Actions environment
          publish_dir: ./dist # Adjust if necessary
