name: Sync Fork and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (adjust the cron if needed)
  workflow_dispatch:  # Triggered by manual button click
  push:
    branches:
      - main

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This ensures the full history is pulled for syncing
          fetch-depth: 0

      - name: Fork Sync
        uses: tgymnich/fork-sync@v2.0.10
        with:
          base: main
          head: main
          merge_method: rebase

      - name: Set up Node.js (if you're using a Node.js-based project like React, Vue, etc.)
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Create .env file for build
        run: |
          echo "VITE_ADMIN_PATH=${{ secrets.VITE_ADMIN_PATH }}" >> .env
          echo "VITE_SERVER_API_URL=${{ secrets.VITE_SERVER_API_URL }}" >> .env

      - name: Build the project
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically available in your GitHub Actions environment
          publish_dir: ./dist  # Adjust if necessary
